web_crm/urls.py
from django.conf.urls import url
from django.contrib import admin

from stark.service import stark
from crm import views
import xadmin

urlpatterns = [
    # url(r'^admin/', admin.site.urls),
    url(r'^admin/', xadmin.site.urls),
    url(r'^stark/',stark.site.urls),
    url(r'^login/', views.login),
]

crm/models.py
from django.db import models

# Create your models here.



class Department(models.Model):
    """
    部门表
    如：
        市场部     1000
        销售       1001

    """
    title = models.CharField(verbose_name='部门名称', max_length=16)
    code = models.IntegerField(verbose_name='部门编号', unique=True, null=False)

    def __str__(self):
        return self.title

from rbac.models import User
class UserInfo(models.Model):
    """
    员工表
    """
    name = models.CharField(verbose_name='员工姓名', max_length=16)
    # username = models.CharField(verbose_name='用户名', max_length=32)
    # password = models.CharField(verbose_name='密码', max_length=64)
    email = models.EmailField(verbose_name='邮箱', max_length=64)

    depart = models.ForeignKey(verbose_name='部门', to="Department", to_field="code")
    # user = models.OneToOneField(to="User", null=True)
    user = models.OneToOneField("rbac.User", null=True)

    def __str__(self):
        return self.name


class Course(models.Model):
    """
    课程表
    如：
        Linux基础
        Linux架构师
        Python自动化开发精英班
        Python自动化开发架构师班
        Python基础班
        go基础班
    """
    name = models.CharField(verbose_name='课程名称', max_length=32)

    def __str__(self):
        return self.name


class School(models.Model):
    """
    校区表
    如：
        北京沙河校区
        上海校区

    """
    title = models.CharField(verbose_name='校区名称', max_length=32)

    def __str__(self):
        return self.title


class ClassList(models.Model):
    """
    班级表
    如：
        Python全栈  面授班  5期  10000  2017-11-11  2018-5-11
    """
    school = models.ForeignKey(verbose_name='校区', to='School')
    course = models.ForeignKey(verbose_name='课程名称', to='Course')

    semester = models.IntegerField(verbose_name="班级(期)")
    price = models.IntegerField(verbose_name="学费")
    start_date = models.DateField(verbose_name="开班日期")
    graduate_date = models.DateField(verbose_name="结业日期", null=True, blank=True)
    memo = models.CharField(verbose_name='说明', max_length=256, blank=True, null=True, )
    # teachers = models.ManyToManyField(verbose_name='任课老师', to='UserInfo',related_name="abc",limit_choices_to={"depart__in":[1002,1005]})
    # tutor = models.ForeignKey(verbose_name='班主任', to='UserInfo', related_name='classes',limit_choices_to={"depart":1001})

    teachers = models.ManyToManyField(verbose_name='任课老师', to='UserInfo', related_name="abcd", limit_choices_to={"depart__in": [1002,1005]})
    tutor = models.ForeignKey(verbose_name='班主任', to='UserInfo', related_name='classes', limit_choices_to={"depart": 1001})

    def __str__(self):
        return "{0}({1}期)".format(self.course.name, self.semester)


class Customer(models.Model):
    """
    客户表
    """
    qq = models.CharField(verbose_name='qq', max_length=64, unique=True, help_text='QQ号必须唯一')

    name = models.CharField(verbose_name='学生姓名', max_length=16)
    gender_choices = ((1, '男'), (2, '女'))
    gender = models.SmallIntegerField(verbose_name='性别', choices=gender_choices)

    education_choices = (
        (1, '重点大学'),
        (2, '普通本科'),
        (3, '独立院校'),
        (4, '民办本科'),
        (5, '大专'),
        (6, '民办专科'),
        (7, '高中'),
        (8, '其他')
    )
    education = models.IntegerField(verbose_name='学历', choices=education_choices, blank=True, null=True, )
    graduation_school = models.CharField(verbose_name='毕业学校', max_length=64, blank=True, null=True)
    major = models.CharField(verbose_name='所学专业', max_length=64, blank=True, null=True)

    experience_choices = [
        (1, '在校生'),
        (2, '应届毕业'),
        (3, '半年以内'),
        (4, '半年至一年'),
        (5, '一年至三年'),
        (6, '三年至五年'),
        (7, '五年以上'),
    ]
    experience = models.IntegerField(verbose_name='工作经验', blank=True, null=True, choices=experience_choices)
    work_status_choices = [
        (1, '在职'),
        (2, '无业')
    ]
    work_status = models.IntegerField(verbose_name="职业状态", choices=work_status_choices, default=1, blank=True,
                                      null=True)
    company = models.CharField(verbose_name="目前就职公司", max_length=64, blank=True, null=True)
    salary = models.CharField(verbose_name="当前薪资", max_length=64, blank=True, null=True)

    source_choices = [
        (1, "qq群"),
        (2, "内部转介绍"),
        (3, "官方网站"),
        (4, "百度推广"),
        (5, "360推广"),
        (6, "搜狗推广"),
        (7, "腾讯课堂"),
        (8, "广点通"),
        (9, "高校宣讲"),
        (10, "渠道代理"),
        (11, "51cto"),
        (12, "智汇推"),
        (13, "网盟"),
        (14, "DSP"),
        (15, "SEO"),
        (16, "其它"),
    ]
    source = models.SmallIntegerField('客户来源', choices=source_choices, default=1)
    referral_from = models.ForeignKey(
        'self',
        blank=True,
        null=True,
        verbose_name="转介绍自学员",
        help_text="若此客户是转介绍自内部学员,请在此处选择内部学员姓名",
        related_name="internal_referral"
    )
    course = models.ManyToManyField(verbose_name="咨询课程", to="Course")

    status_choices = [
        (1, "已报名"),
        (2, "未报名")
    ]
    status = models.IntegerField(
        verbose_name="状态",
        choices=status_choices,
        default=2,
        help_text=u"选择客户此时的状态"
    )

    consultant = models.ForeignKey(verbose_name="课程顾问", to='UserInfo', related_name='consultanter',
                                   limit_choices_to={'depart_id': 1001})

    date = models.DateField(verbose_name="咨询日期", auto_now_add=True)
    recv_date = models.DateField(verbose_name="当前课程顾问的接单日期", null=True)
    last_consult_date = models.DateField(verbose_name="最后跟进日期", )

    def __str__(self):
        # return "姓名:{0},QQ:{1}".format(self.name, self.qq)
        return self.name


class ConsultRecord(models.Model):
    """
    客户跟进记录
    """
    customer = models.ForeignKey(verbose_name="所咨询客户", to='Customer')
    consultant = models.ForeignKey(verbose_name="跟踪人", to='UserInfo')
    date = models.DateField(verbose_name="跟进日期", auto_now_add=True)
    note = models.TextField(verbose_name="跟进内容...")

    def __str__(self):
        return self.customer.name + ":" + self.consultant.name


class Student(models.Model):
    """
    学生表（已报名）
    """
    customer = models.OneToOneField(verbose_name='客户信息', to='Customer')

    username = models.CharField(verbose_name='用户名', max_length=32)
    password = models.CharField(verbose_name='密码', max_length=64)
    emergency_contract = models.CharField(max_length=32, blank=True, null=True, verbose_name='紧急联系人')

    class_list = models.ManyToManyField(verbose_name="已报班级", to='ClassList', blank=True)
    company = models.CharField(verbose_name='公司', max_length=128, blank=True, null=True)
    location = models.CharField(max_length=64, verbose_name='所在区域', blank=True, null=True)
    position = models.CharField(verbose_name='岗位', max_length=64, blank=True, null=True)
    salary = models.IntegerField(verbose_name='薪资', blank=True, null=True)
    welfare = models.CharField(verbose_name='福利', max_length=256, blank=True, null=True)
    date = models.DateField(verbose_name='入职时间', help_text='格式yyyy-mm-dd', blank=True, null=True)
    memo = models.CharField(verbose_name='备注', max_length=256, blank=True, null=True)

    def __str__(self):
        return self.username


class CourseRecord(models.Model):
    """
    上课记录表 （班级记录）
    """
    class_obj = models.ForeignKey(verbose_name="班级", to="ClassList")
    day_num = models.IntegerField(verbose_name="节次", help_text=u"此处填写第几节课或第几天课程...,必须为数字")
    teacher = models.ForeignKey(verbose_name="讲师", to='UserInfo',limit_choices_to={"depart_id__in":[1002,1003]})
    date = models.DateField(verbose_name="上课日期", auto_now_add=True)

    course_title = models.CharField(verbose_name='本节课程标题', max_length=64, blank=True, null=True)
    course_memo = models.TextField(verbose_name='本节课程内容概要', blank=True, null=True)
    has_homework = models.BooleanField(default=True, verbose_name="本节有作业")
    homework_title = models.CharField(verbose_name='本节作业标题', max_length=64, blank=True, null=True)
    homework_memo = models.TextField(verbose_name='作业描述', max_length=500, blank=True, null=True)
    exam = models.TextField(verbose_name='踩分点', max_length=300, blank=True, null=True)

    def __str__(self):
        return "{0} day{1}".format(self.class_obj, self.day_num)


class StudyRecord(models.Model):
    '''
    学生记录
    '''
    course_record = models.ForeignKey(verbose_name="第几天课程", to="CourseRecord")
    student = models.ForeignKey(verbose_name="学员", to='Student')
    record_choices = (('checked', "已签到"),
                      ('vacate', "请假"),
                      ('late', "迟到"),
                      ('noshow', "缺勤"),
                      ('leave_early', "早退"),
                      )
    record = models.CharField("上课纪录", choices=record_choices, default="checked", max_length=64)
    score_choices = ((100, 'A+'),
                     (90, 'A'),
                     (85, 'B+'),
                     (80, 'B'),
                     (70, 'B-'),
                     (60, 'C+'),
                     (50, 'C'),
                     (40, 'C-'),
                     (0, ' D'),
                     (-1, 'N/A'),
                     (-100, 'COPY'),
                     (-1000, 'FAIL'),
                     )
    score = models.IntegerField("本节成绩", choices=score_choices, default=-1)
    homework_note = models.CharField(verbose_name='作业评语', max_length=255, blank=True, null=True)
    note = models.CharField(verbose_name="备注", max_length=255, blank=True, null=True)

    homework = models.FileField(verbose_name='作业文件', blank=True, null=True, default=None)
    stu_memo = models.TextField(verbose_name='学员备注', blank=True, null=True)
    date = models.DateTimeField(verbose_name='提交作业日期', auto_now_add=True)

    def __str__(self):
        return "{0}-{1}".format(self.course_record, self.student)

class CustomerDistrbute(models.Model):
    customer = models.ForeignKey("Customer", related_name="customers")
    consultant = models.ForeignKey(verbose_name="课程顾问", to="UserInfo", limit_choices_to={"depart_id": 1001})
    date = models.DateField()

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.min.css">
    <style>
        .header{width: 100%; height: 60px; background-color: #336699;}
        .menu{background-color: bisque; position: fixed; top: 60px; bottom: 0;left: 0;width: 200px;}
        .content{ position: fixed; top: 60px;bottom: 0;right: 0; left: 200px;overflow: auto; padding: 20px;}

        .menu_btn{ font-size: 18px;text-align: center; padding: 10px 0;}


    </style>
</head>
<body>

<div class="header">
    <p>{{ user.name }}</p>
</div>

<div class="container">
    {% load my_tags %}
    <div class="menu">
        {% get_menu request %}
    </div>

    <div class="content">
        {% block content %}

        {% endblock content %}
    </div>
</div>

</body>
</html>

templates/login.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>

    <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.min.css">
    <style>
        .container_top{
            margin-top: 100px;
        }
    </style>
</head>
<body>
<div class="container container_top">
    <div class="row">
        <div class="col-sm-6 col-sm-offset-3 col-md-4 col-md-offset-4">
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <h2 class="my_center">请输入用户名和密码</h2>
                    <p class="my_center">Enter your username and password to log on:</p>
                </div>
                <div class="panel-body">
                    <form action='' method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="user">用户：</label>
                            <input type="text" name="user" class="form-control">
                        </div>

                        <div class="form-group">
                            <label for="pwd">密码：</label>
                            <input type="password" name="pwd" class="form-control">
                        </div>

                        <div class="form-group" style="margin-top: 2em">
                            <input type="submit" class=" btn btn-info btn-block btn3d login_btn" value="Login">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


</body>
</html>

templates/mycustomer.html
{% extends "base.html" %}


{% block content %}
<h4>我的客户</h4>
<ul>
    {% for customer_distrubute in customer_distrubute_list %}
        <li>
            {{ customer_distrubute.customer }}
            -----{{ customer_distrubute.date|date:'Y-m-d' }}
            -----{{ customer_distrubute.get_status_display }}
        </li>
    {% endfor %}
</ul>

{% endblock content %}

templates/public.html
{% extends "base.html" %}


{% block content %}
<h3>公共客户</h3>

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <table class="table table-bordered table-striped">
                <thead>
                   <tr>
                       <th>ID</th>
                       <th>姓名</th>
                       <th>QQ</th>
                       <th>课程顾问</th>
                       <th>跟进详情</th>
                       <th>确认跟进</th>
                   </tr>
                </thead>

                <tbody>
                    {% for customer in customer_list %}

                    <tr>
                        <td>{{ forloop.counter }}</td>
                        <td>{{ customer.name }}</td>
                        <td>{{ customer.qq }}</td>
                        <td>{{ customer.consultant }}</td>
                        <td><a href="/stark/crm/consultrecord/?customer={{ customer.pk }}">跟进记录</a></td>
                        <td><a href="/stark/crm/customer/further/{{ customer.pk }}">确认跟进</a></td>
                    </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock content %}

templates/score.html
{% extends "base.html" %}

{% block content %}
<h3>录入成绩</h3>

<div class="container">
    <div class="row">
        <div class="col-md-9 col-md-offset-1">
            <form action="" method="post">
                 {% csrf_token %}
                 <table class="table-bordered table table-striped">
                <thead>
                    <tr>
                        <th>学生姓名</th>
                        <th>考勤</th>
                        <th>成绩</th>
                        <th>批语</th>
                    </tr>
                </thead>

                <tbody>
                      {% for study_record in study_record_list %}
                        <tr>
                            <td>{{ study_record.student}}</td>
                            <td>{{ study_record.get_record_display }}</td>
                            <td style="width: 150px;padding: 10px 20px">

                                <select name="score_{{ study_record.pk }}" id="" class="form-control" >
                                    {% for item in score_choices %}
                                        {% if study_record.score == item.0 %}
                                        <option selected value="{{ item.0 }}">{{ item.1 }}</option>
                                        {% endif %}
                                        <option value="{{ item.0 }}">{{ item.1 }}</option>
                                    {% endfor %}

                                </select>

                            </td>
                            <td>
                                <textarea name="homework_note_{{ study_record.pk }}" id="" cols="30" rows="3" class="form-control">{{ study_record.homework_note }}</textarea>
                            </td>
                        </tr>
                      {% endfor %}

                </tbody>
            </table>
                <input type="submit" class="btn btn-success pull-right">
            </form>
        </div>
    </div>
</div>

{% endblock content %}

templates/score_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/bootstrap-3.3.7/css/bootstrap.min.css">
    <script src="/static/js/jquery-3.2.1.min.js"></script>
    <script src="/static/hchart/highcharts.js"></script>
    <script src="/static/hchart/highcharts-3d.js"></script>
    <script src="/static/hchart/modules/exporting.js"></script>
    <script src="/static/echarts/echarts.min.js"></script>
</head>
<body><h3>查看 [{{ student }}] 成绩</h3>

<div class="container">
    <div class="row">
        <div class="col-md-9">
            <form action="">
                <table class="table-bordered table table-striped">
                    <thead>
                    <tr>
                        <th>班级</th>
                        <th>班主任</th>
                        <th>任课老师</th>
                        <th>课程成绩</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for cls in class_list %}
                        <tr>
                            <td>{{ cls }}</td>
                            <td>{{ cls.tutor }}</td>
                            <td>
                                {% for teacher in cls.teachers.all %}
                                    <span>{{ teacher }}</span>,
                                {% endfor %}

                            </td>
                            <td>
                                <a class="check_chart" cid="{{ cls.pk }}" sid="{{ student.pk }}">查看成绩</a>
                            </td>
                        </tr>
                    {% endfor %}

                    </tbody>
                </table>
            </form>
        </div>
    </div>
</div>

<div class="col-md-offset-1" id="container" style="width: 500px; height: 400px;"></div>

<script type="text/javascript">
    $('.check_chart').click(function () {
        $.ajax({
            url: "",
            type: "get",
            data: {
                cid: $(this).attr('cid'),
                sid: $(this).attr('sid')
            },
            success: function (data) {
                var chart = Highcharts.chart('container', {
                    chart: {
                        type: 'column',  //图表类型 line, spline, area, areaspline, column, bar, pie , scatter
                        options3d: {
                            enabled: true,
                            alpha: 10,
                            beta: 25,
                            depth: 70
                        }
                    },
                    title: {
                        text: '查看学生每天的成绩'
                    },
                    subtitle: {
                        text: "数据截止 2017-07"
                    },
                    xAxis: {

                        {#type: 'category',#}
                        {##}
                        {#labels: {#}
                        {##}
                        {#    rotation: -45  // 设置轴标签旋转角度#}
                        {##}
                        {#    categories: ['day60', 'day60']#}
                        },
                        yAxis: {
                            min: 0,
                            title: {
                                text: '分数'
                            }
                        },
                        legend: {
                            enabled: false
                        },
                        tooltip: {
                            pointFormat: '分数:'
                        },
                        plotOptions: {
                            column: {
                                allowPointSelect: true,
                                cursor: 'pointer',
                                depth: 35,
                                dataLabels: {
                                    enabled: true,
                                    format: '{point.name}'
                                }
                            }
                        },
                        series: [{

                            {#type: 'pie',#}
                            name: '总人口',
                            data: data,
                            dataLabels: {
                                enabled: true,
                                rotation: 1,
                                color: '#FFFFFF',
                                align: 'right',
                                format: '{point.y:.1f}', // :.1f 为保留 1 位小数
                                y: 10
                            }
                        }],
                        credits: {
                            enabled: false // 禁用版权信息
                        },
                    });

            }
        });
    });
    Highcharts.setOptions({
        lang: {
            contextButtonTitle: "图表导出菜单",
            decimalPoint: ".",
            downloadJPEG: "下载JPEG图片",
            downloadPDF: "下载PDF文件",
            downloadPNG: "下载PNG文件",
            downloadSVG: "下载SVG文件",
            drillUpText: "返回 {series.name}",
            loading: "加载中",
            printChart: "打印图表",
            resetZoom: "恢复缩放",
            resetZoomTitle: "恢复图表",
        }
    });

</script>

</body>
</html>